ALTER SESSION SET CURRENT_SCHEMA = SECURITY;

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE CAT_STATUS_MENSAJE CASCADE CONSTRAINTS ';
EXCEPTION WHEN OTHERS THEN NULL ;
end;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_STATUS_MENSAJE';
    EXCEPTION WHEN OTHERS THEN NULL;
end;
/

CREATE TABLE CAT_STATUS_MENSAJE(
    ID_STATUS_MENSAJE VARCHAR2(15) NOT NULL,
    NOMBRE_STATUS VARCHAR2(40) NOT NULL,
    DESCRIPCION VARCHAR2(100) NOT NULL,
    ESTADO NUMBER(2) DEFAULT 1 NOT NULL,
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREADO_POR VARCHAR2(36) NOT NULL,
    FECHA_ACTUALIZACION TIMESTAMP,
    ACTUALIZADO_POR VARCHAR2(36),
    NOTAS VARCHAR2(100),
    CONSTRAINT pk_id_cat_status_mensaje PRIMARY KEY (ID_STATUS_MENSAJE)
);

COMMENT ON TABLE CAT_STATUS_MENSAJE IS 'Tabla de estados del mensaje de contacto';
COMMENT ON COLUMN CAT_STATUS_MENSAJE.ID_STATUS_MENSAJE IS 'Id del estado';
COMMENT ON COLUMN CAT_STATUS_MENSAJE.NOMBRE_STATUS IS 'Estado del mensaje';
COMMENT ON COLUMN CAT_STATUS_MENSAJE.DESCRIPCION IS 'Descripción del estado';
COMMENT ON COLUMN CAT_STATUS_MENSAJE.ESTADO IS 'Estado del registro';
COMMENT ON COLUMN CAT_STATUS_MENSAJE.FECHA_CREACION IS 'Fecha creación';
COMMENT ON COLUMN CAT_STATUS_MENSAJE.CREADO_POR IS 'Usuario creador';
COMMENT ON COLUMN CAT_STATUS_MENSAJE.FECHA_ACTUALIZACION IS 'Fecha actualización';
COMMENT ON COLUMN CAT_STATUS_MENSAJE.ACTUALIZADO_POR IS 'Usuario que actualizó';
COMMENT ON COLUMN CAT_STATUS_MENSAJE.NOTAS IS 'Observaciones';
COMMIT;

CREATE SEQUENCE SEQ_STATUS_MENSAJE START WITH 0 INCREMENT BY 1 MINVALUE 0 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_STATUS_MENSAJE_ID
BEFORE INSERT ON CAT_STATUS_MENSAJE
FOR EACH ROW
BEGIN
    IF :NEW.ID_STATUS_MENSAJE IS NULL THEN
        :NEW.ID_STATUS_MENSAJE := 'CSM-' || LPAD(SEQ_STATUS_MENSAJE.NEXTVAL, 3, '0');
    end if;
end;

INSERT INTO CAT_STATUS_MENSAJE(NOMBRE_STATUS, DESCRIPCION, CREADO_POR)
VALUES('RECIBIDO', 'MENSAJE RECIBIDO POR EL ADMINISTRADOR', '57e8cc9c-9d83-4e76-99c1-d6de3d7a984e');

INSERT INTO CAT_STATUS_MENSAJE(NOMBRE_STATUS, DESCRIPCION, CREADO_POR)
VALUES('LEIDO', 'MENSAJE LEIDO POR EL ADMINISTRADOR', '57e8cc9c-9d83-4e76-99c1-d6de3d7a984e');

INSERT INTO CAT_STATUS_MENSAJE(NOMBRE_STATUS, DESCRIPCION, CREADO_POR)
VALUES('CONTESTADO', 'MENSAJE CONTESTADO POR EL ADMINISTRADOR', '57e8cc9c-9d83-4e76-99c1-d6de3d7a984e');