ALTER SESSION SET CURRENT_SCHEMA = SECURITY;

BEGIN
    EXECUTE IMMEDIATE  'DROP TABLE CAT_TIPO_TOKEN CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
end;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_TIPO_TOKEN';
EXCEPTION WHEN OTHERS THEN NULL;
end;
/

CREATE TABLE CAT_TIPO_TOKEN (
    ID_TIPO_TOKEN VARCHAR2(15) NOT NULL,
    NOMBRE_TOKEN VARCHAR2(50) NOT NULL,
    DESCRIPCION VARCHAR2(100),
    ESTADO NUMBER(2) DEFAULT 0 NOT NULL,
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREADO_POR VARCHAR2(36) NOT NULL,
    FECHA_ACTUALIZACION TIMESTAMP,
    ACTUALIZADO_POR VARCHAR2(36),
    NOTAS VARCHAR2(100),
    CONSTRAINT PK_TIPO_TOKEN PRIMARY KEY (ID_TIPO_TOKEN),
    CONSTRAINT CK_ESTADO_TOKEN CHECK (ESTADO IN (0, 99))
);

COMMENT ON TABLE CAT_TIPO_TOKEN IS 'Tabla catálogo de tipo token';
COMMENT ON COLUMN CAT_TIPO_TOKEN.ID_TIPO_TOKEN IS 'Clave del tipo de token RL-001';
COMMENT ON COLUMN CAT_TIPO_TOKEN.NOMBRE_TOKEN IS 'Nombre del token';
COMMENT ON COLUMN CAT_TIPO_TOKEN.DESCRIPCION IS 'Descripción del token';
COMMENT ON COLUMN CAT_TIPO_TOKEN.ESTADO IS '0 = Inactivo, 99 = Activo';
COMMENT ON COLUMN CAT_TIPO_TOKEN.FECHA_CREACION IS 'Fecha creación';
COMMENT ON COLUMN CAT_TIPO_TOKEN.CREADO_POR IS 'Usuario creador';
COMMENT ON COLUMN CAT_TIPO_TOKEN.FECHA_ACTUALIZACION IS 'Fecha actualización';
COMMENT ON COLUMN CAT_TIPO_TOKEN.ACTUALIZADO_POR IS 'Usuario que actualizó';
COMMENT ON COLUMN CAT_TIPO_TOKEN.NOTAS IS 'Observaciones';

CREATE SEQUENCE SEQ_TIPO_TOKEN START WITH 0 INCREMENT BY 1 MINVALUE 0 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_TIPO_TOKEN_ID
BEFORE INSERT ON CAT_TIPO_TOKEN
FOR EACH ROW
BEGIN
    IF :NEW.ID_TIPO_TOKEN IS NULL THEN
        :NEW.ID_TIPO_TOKEN := 'CTK-' || LPAD(SEQ_TIPO_TOKEN.NEXTVAL, 3, '0');
    end if;
end;
/

INSERT INTO CAT_TIPO_TOKEN (NOMBRE_TOKEN, DESCRIPCION, CREADO_POR)
VALUES ('EMAIL_VERIFY', 'VERIFICAR PERFIL DE USUARIO', '57e8cc9c-9d83-4e76-99c1-d6de3d7a984e');

INSERT INTO CAT_TIPO_TOKEN (NOMBRE_TOKEN, DESCRIPCION, CREADO_POR)
VALUES ('RESET_PASSWORD', 'CAMBIO DE PASSWORD', '57e8cc9c-9d83-4e76-99c1-d6de3d7a984e');

INSERT INTO CAT_TIPO_TOKEN (NOMBRE_TOKEN, DESCRIPCION, CREADO_POR)
VALUES ('REACTIVACION', 'REACTIVAR CUENTA', '57e8cc9c-9d83-4e76-99c1-d6de3d7a984e');

COMMIT;

SELECT * FROM CAT_TIPO_TOKEN;