ALTER SESSION SET CURRENT_SCHEMA = SECURITY;

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE CAT_TIPO_CLIENTE CASCADE CONSTRAINTS ';
    EXCEPTION WHEN OTHERS THEN NULL;
end;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_TIPO_CLIENTE_ID';
    EXCEPTION WHEN OTHERS THEN NULL;
end;
/

CREATE TABLE CAT_TIPO_CLIENTE (
    ID_TIPO_CLIENTE VARCHAR2(15) NOT NULL,
    NOMBRE VARCHAR2(50) NOT NULL,
    DESCRIPCION VARCHAR2(100),
    ESTADO NUMBER(2) DEFAULT 0 NOT NULL,
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREADO_POR VARCHAR2(36) NOT NULL,
    FECHA_ACTUALIZACION TIMESTAMP,
    ACTUALIZADO_POR VARCHAR2(36),
    NOTAS VARCHAR2(100),
    CONSTRAINT PK_TIPO_CLIENTE PRIMARY KEY (ID_TIPO_CLIENTE),
    CONSTRAINT CK_TIPO_CLIENTE CHECK (ESTADO IN (0, 99))
);

COMMENT ON TABLE CAT_TIPO_CLIENTE IS 'Tabla catálogo de tipo de estados para factura';
COMMENT ON COLUMN CAT_TIPO_CLIENTE.ID_TIPO_CLIENTE IS 'Clave de estado de la factura RL-001';
COMMENT ON COLUMN CAT_TIPO_CLIENTE.NOMBRE IS 'Nombre del estado de la factua';
COMMENT ON COLUMN CAT_TIPO_CLIENTE.DESCRIPCION IS 'Descripción del estado';
COMMENT ON COLUMN CAT_TIPO_CLIENTE.ESTADO IS '0 = Inactivo, 99 = Activo';
COMMENT ON COLUMN CAT_TIPO_CLIENTE.FECHA_CREACION IS 'Fecha creación';
COMMENT ON COLUMN CAT_TIPO_CLIENTE.CREADO_POR IS 'Usuario creador';
COMMENT ON COLUMN CAT_TIPO_CLIENTE.FECHA_ACTUALIZACION IS 'Fecha de actualización';
COMMENT ON COLUMN CAT_TIPO_CLIENTE.ACTUALIZADO_POR IS 'Usuario que actualizó';
COMMENT ON COLUMN CAT_TIPO_CLIENTE.NOTAS IS 'Observaciones';

CREATE SEQUENCE SEQ_TIPO_CLIENTE_ID START WITH 0 INCREMENT BY 1 MINVALUE 0 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_ID_TIPO_CLIENTE
BEFORE INSERT ON CAT_TIPO_CLIENTE
FOR EACH ROW
BEGIN
    IF :NEW.ID_TIPO_CLIENTE IS NULL THEN
        :NEW.ID_TIPO_CLIENTE := 'TCLI' || LPAD(SEQ_TIPO_CLIENTE_ID.NEXTVAL, 3, '0');
end if;
end;
/

INSERT INTO CAT_TIPO_CLIENTE (NOMBRE, DESCRIPCION, CREADO_POR)
VALUES ('MORAL', 'PERSONA MORAL O EMPRESA', '57e8cc9c-9d83-4e76-99c1-d6de3d7a984e');

INSERT INTO CAT_TIPO_CLIENTE (NOMBRE, DESCRIPCION, CREADO_POR)
VALUES ('FISICA', 'PERSONA MORAL O EMPRESA', '57e8cc9c-9d83-4e76-99c1-d6de3d7a984e');

INSERT INTO CAT_TIPO_CLIENTE (NOMBRE, DESCRIPCION, CREADO_POR)
VALUES ('GENERICA', 'PERSONA MORAL O EMPRESA', '57e8cc9c-9d83-4e76-99c1-d6de3d7a984e');