ALTER SESSION SET CURRENT_SCHEMA = SECURITY;

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE CLIENTES_BIT CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
end;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_CLIENTE_ID';
EXCEPTION WHEN OTHERS THEN NULL;
end;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE CLIENTES CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
end;
/

CREATE TABLE CLIENTES (
    ID_CLIENTE VARCHAR2(36) NOT NULL,
    NOMBRE VARCHAR2(40) NOT NULL,
    APATERNO VARCHAR(40) NOT NULL,
    AMATERNO VARCHAR2(40),
    EMAIL VARCHAR2(100),
    FECHA_ALTA DATE DEFAULT SYSDATE,
    ESTADO NUMBER(2) DEFAULT 0 NOT NULL,
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREADO_POR VARCHAR2(36) NOT NULL,
    FECHA_ACTUALIZACION TIMESTAMP,
    ACTUALIZADO_POR VARCHAR2(36),
    NOTAS VARCHAR2(100),
    CONSTRAINT pk_id_cliente_clientes PRIMARY KEY (ID_CLIENTE)
);

COMMENT ON TABLE CLIENTES IS 'Tabla que contiene la información del cliente';
COMMENT ON COLUMN CLIENTES.ID_CLIENTE IS 'Llave primaria de la tabla';
COMMENT ON COLUMN CLIENTES.NOMBRE IS 'Nombre del cliente';
COMMENT ON COLUMN CLIENTES.APATERNO IS 'Apellido paterno';
COMMENT ON COLUMN CLIENTES.AMATERNO IS 'Apellido materno';
COMMENT ON COLUMN CLIENTES.EMAIL IS 'Email del cliente';
COMMENT ON COLUMN CLIENTES.FECHA_ALTA IS 'Fecha de alta del cliente';
COMMENT ON COLUMN CLIENTES.ESTADO IS 'Bandera para borrado logico';
COMMENT ON COLUMN CLIENTES.FECHA_CREACION IS 'Fecha de creación';
COMMENT ON COLUMN CLIENTES.CREADO_POR IS 'Usuario creador';
COMMENT ON COLUMN CLIENTES.FECHA_ACTUALIZACION IS 'Fecha actualización';
COMMENT ON COLUMN CLIENTES.ACTUALIZADO_POR IS 'Usuario que actualizó';
COMMENT ON COLUMN CLIENTES.NOTAS IS 'Observaciones';

CREATE SEQUENCE SEQ_CLIENTE_ID START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_CLIENTE_ID
BEFORE INSERT ON CLIENTES
FOR EACH ROW
BEGIN
    IF :NEW.ID_CLIENTE IS NULL THEN
        :NEW.ID_CLIENTE := 'CLI-' || LPAD(SEQ_CLIENTE_ID.NEXTVAL, 6, '0');
    end if;
end;

CREATE TABLE CLIENTES_BIT (
    ID_CLIENTE_BIT VARCHAR2(36) NOT NULL,
    ID_CLIENTE VARCHAR2(36) NOT NULL,
    NOMBRE VARCHAR2(40) NOT NULL,
    APATERNO VARCHAR2(40) NOT NULL,
    AMATERNO VARCHAR2(40) NOT NULL,
    EMAIL VARCHAR2(100),
    FECHA_ALTA DATE DEFAULT SYSDATE,
    ESTADO NUMBER(2) NOT NULL,
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREADO_POR VARCHAR2(36) NOT NULL,
    FECHA_ACTUALIZACION TIMESTAMP,
    ACTUALIZADO_POR VARCHAR2(36),
    NOTAS VARCHAR2(100),
    ACCION VARCHAR2(10) NOT NULL,
    IP VARCHAR2(30) NOT NULL,
    CONSTRAINT pk_id_cliente_bit_clientes_bit PRIMARY KEY (ID_CLIENTE_BIT)
);

COMMENT ON TABLE CLIENTES_BIT IS 'Tabla de bitácora para la tabla Clientes';
COMMENT ON COLUMN CLIENTES_BIT.ID_CLIENTE_BIT IS 'Clave primaria';
COMMENT ON COLUMN CLIENTES_BIT.ID_CLIENTE IS 'Id del cliente, llave foranea';
COMMENT ON COLUMN CLIENTES_BIT.NOMBRE IS 'Nombre del cliente';
COMMENT ON COLUMN CLIENTES_BIT.APATERNO IS 'Apellido paterno';
COMMENT ON COLUMN CLIENTES_BIT.AMATERNO IS 'Apellido materno';
COMMENT ON COLUMN CLIENTES_BIT.EMAIL IS 'Email del cliente';
COMMENT ON COLUMN CLIENTES_BIT.FECHA_ALTA IS 'Alta del cliente';
COMMENT ON COLUMN CLIENTES_BIT.ESTADO IS 'Bandera de borrado logico';
COMMENT ON COLUMN CLIENTES_BIT.FECHA_CREACION IS 'Fecha de creación';
COMMENT ON COLUMN CLIENTES_BIT.CREADO_POR IS 'Usuario creador';
COMMENT ON COLUMN CLIENTES_BIT.FECHA_ACTUALIZACION IS 'Fecha actualización';
COMMENT ON COLUMN CLIENTES_BIT.ACTUALIZADO_POR IS 'Usuario que actualizó';
COMMENT ON COLUMN CLIENTES_BIT.NOTAS IS 'Observaciones';
COMMENT ON COLUMN CLIENTES_BIT.ACCION IS 'Accion en el registro';
COMMENT ON COLUMN CLIENTES_BIT.IP IS 'IP de quién el cambio';

CREATE OR REPLACE TRIGGER TRG_CLIENTES_AUD
AFTER INSERT OR UPDATE ON CLIENTES
FOR EACH ROW
DECLARE
    V_ACCION VARCHAR2(20);
    V_FECHA_CREACION DATE := NULL;
    V_FECHA_MODIFICACION DATE := NULL;
BEGIN
    -- INSERT
    IF INSERTING THEN
        V_ACCION:= 'INSERT';
        V_FECHA_CREACION := SYSDATE;

    -- UPDATE
    ELSIF UPDATING THEN
        V_FECHA_MODIFICACION := SYSDATE;
        V_FECHA_CREACION := :OLD.FECHA_ALTA;
        -- Detectar borrado lógico
        IF :OLD.ESTADO = 1 AND :NEW.ESTADO = 0 THEN
            V_ACCION := 'DEACTIVATE';
        ELSIF :OLD.ESTADO = 0 AND :NEW.ESTADO = 1 THEN
            V_ACCION := 'ACTIVATE';
        ELSE
            V_ACCION := 'UPDATE';
        END IF;
    END IF;

    INSERT INTO CLIENTES_BIT (ID_CLIENTE_BIT, ID_CLIENTE, NOMBRE, APATERNO, AMATERNO, EMAIL, FECHA_ALTA, ESTADO, FECHA_CREACION,
    FECHA_ACTUALIZACION, CREADO_POR, ACTUALIZADO_POR, NOTAS, ACCION, IP)
    VALUES(
        SYS_GUID(),
           :NEW.ID_CLIENTE,
           :NEW.NOMBRE,
           :NEW.APATERNO,
           :NEW.AMATERNO,
           :NEW.EMAIL,
           :NEW.FECHA_ALTA,
           :NEW.ESTADO,
           V_FECHA_CREACION,
           V_FECHA_MODIFICACION,
           :NEW.CREADO_POR,
           :NEW.ACTUALIZADO_POR,
           :NEW.NOTAS,
        V_ACCION,
           FN_GET_IP()
    );
end;