ALTER SESSION SET CURRENT_SCHEMA = SECURITY;

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_DATOSFISC_ID';
EXCEPTION WHEN OTHERS THEN NULL;
end;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE DATOS_FISCALES CASCADE CONSTRAINTS ';
EXCEPTION WHEN OTHERS THEN NULL;
end;
/

CREATE TABLE DATOS_FISCALES (
    ID_DATOSFISC VARCHAR2(36) NOT NULL,
    ID_CLIENTE VARCHAR2(36) NOT NULL,
    RAZON_SOCIAL VARCHAR2(150) NOT NULL,
    RFC VARCHAR2(13) NOT NULL,
    CODIGO_POSTAL VARCHAR2(5) NOT NULL,
    ID_TIPO_CLIENTE VARCHAR2(3) NOT NULL,
    USO_CFDI VARCHAR2(3) NOT NULL,
    EMAIL VARCHAR2(100),
    D_ESTADO VARCHAR2(36) NOT NULL,
    D_CIUDAD VARCHAR2(36) NOT NULL,
    D_COLONIA VARCHAR2(36) NOT NULL,
    D_ZONA VARCHAR2(36) NOT NULL,
    CREATED_AT DATE DEFAULT SYSDATE,
    STATUS NUMBER(2) NOT NULL,
    CREADO_POR VARCHAR2(36) NOT NULL,
    FECHA_ACTUALIZACION TIMESTAMP,
    ACTUALIZADO_POR VARCHAR2(36),
    NOTAS VARCHAR2(100),
    CONSTRAINT pk_id_datos_fiscales_clientes PRIMARY KEY (ID_DATOSFISC),
    CONSTRAINT uk_rfc_cliente UNIQUE (RFC),
    CONSTRAINT fk_tipo_cliente FOREIGN KEY (ID_TIPO_CLIENTE) REFERENCES CAT_TIPO_CLIENTE (ID_TIPO_CLIENTE),
    CONSTRAINT fk_email_cliente FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES (ID_CLIENTE)
);

COMMENT ON TABLE DATOS_FISCALES IS 'Almacena información fiscal de los clientes para facturar con CFDI 4.0';
COMMENT ON COLUMN DATOS_FISCALES.ID_DATOSFISC IS 'Llave primaria de la tabla';
COMMENT ON COLUMN DATOS_FISCALES.ID_CLIENTE IS 'Identificador (CLI-XXXXXX)';
COMMENT ON COLUMN DATOS_FISCALES.RAZON_SOCIAL IS 'Denominacion social tal cual aparece en SAT';
COMMENT ON COLUMN DATOS_FISCALES.RFC IS 'RFC';
COMMENT ON COLUMN DATOS_FISCALES.CODIGO_POSTAL IS 'Domicilio';
COMMENT ON COLUMN DATOS_FISCALES.ID_TIPO_CLIENTE IS 'Clave del régimen del cliente';
COMMENT ON COLUMN DATOS_FISCALES.USO_CFDI IS 'Uso del CFDI';
COMMENT ON COLUMN DATOS_FISCALES.EMAIL IS 'Email del cliente';
COMMENT ON COLUMN DATOS_FISCALES.D_ESTADO IS 'Estado';
COMMENT ON COLUMN DATOS_FISCALES.D_CIUDAD IS 'Ciudad';
COMMENT ON COLUMN DATOS_FISCALES.D_COLONIA IS 'Colonia';
COMMENT ON COLUMN DATOS_FISCALES.D_ZONA IS 'Zona';
COMMENT ON COLUMN DATOS_FISCALES.CREATED_AT IS 'Fecha creación registro';
COMMENT ON COLUMN DATOS_FISCALES.STATUS IS 'Bandera borrado lógico (1 = Activo, 0 = Inactivo)';
COMMENT ON COLUMN DATOS_FISCALES.CREADO_POR IS 'Usuario creador';
COMMENT ON COLUMN DATOS_FISCALES.FECHA_ACTUALIZACION IS 'Fecha actualizacón';
COMMENT ON COLUMN DATOS_FISCALES.ACTUALIZADO_POR IS 'Usuario que actualizó';
COMMENT ON COLUMN DATOS_FISCALES.NOTAS IS 'Observaciones';

CREATE SEQUENCE SEQ_DATOSFISC_ID START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_DATOS_FISCALES_ID
BEFORE INSERT ON DATOS_FISCALES
FOR EACH ROW
BEGIN
    IF :NEW.ID_DATOSFISC IS NULL THEN
        :NEW.ID_DATOSFISC := 'DATFIC-' || LPAD(SEQ_DATOSFISC_ID.NEXTVAL, 6, '0');
    end if;
end;
/