-- Configurar entorno
ALTER SESSION SET CURRENT_SCHEMA = SECURITY;

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE CAT_STATUS_MENSAJE_ESPEJO CASCADE CONSTRAINTS ';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TRIGGER TRG_CAT_STATUS_MENSAJE_ESPEJO';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

-- Función para obtener IP
CREATE OR REPLACE FUNCTION FN_GET_IP
RETURN VARCHAR2
IS
BEGIN
    RETURN NVL(
        SYS_CONTEXT('USERENV', 'IP_ADDRESS'),
        SYS_CONTEXT('USERENV', 'HOST')
    );

EXCEPTION
    WHEN OTHERS THEN
        RETURN 'LOCALHOST';
END FN_GET_IP;
/

-- Creación de tabla espejo
CREATE TABLE CAT_STATUS_MENSAJE_ESPEJO(
    UUID_STATUS_MENSAJE_ESPEJO VARCHAR2(36) NOT NULL,
    ID_STATUS_MENSAJE VARCHAR2(15) NOT NULL,
    NOMBRE_STATUS VARCHAR2(40) NOT NULL,
    DESCRIPCION VARCHAR2(100) NOT NULL,
    ESTADO NUMBER(2) NOT NULL,
    FECHA_CREACION TIMESTAMP NOT NULL,
    CREADO_POR VARCHAR2(36) NOT NULL,
    FECHA_ACTUALIZACION TIMESTAMP,
    ACTUALIZADO_POR VARCHAR2(36),
    NOTAS VARCHAR2(100),
    ACCION VARCHAR2(20) NOT NULL,
    IP VARCHAR2(30) NOT NULL,

    CONSTRAINT PK_CAT_STATUS_MENSAJE_ESPEJO
    PRIMARY KEY (UUID_STATUS_MENSAJE_ESPEJO)
);

-- Comentarios tabla
COMMENT ON TABLE CAT_STATUS_MENSAJE_ESPEJO IS 'Tabla espejo o bitácora del catálogo de status de mensajes';
COMMENT ON COLUMN CAT_STATUS_MENSAJE_ESPEJO.UUID_STATUS_MENSAJE_ESPEJO IS 'UUID único del registro espejo';
COMMENT ON COLUMN CAT_STATUS_MENSAJE_ESPEJO.ID_STATUS_MENSAJE IS 'Id del estado del mensaje';
COMMENT ON COLUMN CAT_STATUS_MENSAJE_ESPEJO.NOMBRE_STATUS IS 'Nombre del estado del mensaje';
COMMENT ON COLUMN CAT_STATUS_MENSAJE_ESPEJO.DESCRIPCION IS 'Descripción del estado';
COMMENT ON COLUMN CAT_STATUS_MENSAJE_ESPEJO.ESTADO IS 'Estado del registro';
COMMENT ON COLUMN CAT_STATUS_MENSAJE_ESPEJO.FECHA_CREACION IS 'Fecha creación del registro original';
COMMENT ON COLUMN CAT_STATUS_MENSAJE_ESPEJO.CREADO_POR IS 'Usuario creador del registro original';
COMMENT ON COLUMN CAT_STATUS_MENSAJE_ESPEJO.FECHA_ACTUALIZACION IS 'Fecha actualización del registro original';
COMMENT ON COLUMN CAT_STATUS_MENSAJE_ESPEJO.ACTUALIZADO_POR IS 'Usuario que actualizó el registro original';
COMMENT ON COLUMN CAT_STATUS_MENSAJE_ESPEJO.NOTAS IS 'Observaciones adicionales';
COMMENT ON COLUMN CAT_STATUS_MENSAJE_ESPEJO.ACCION IS 'Acción realizada sobre el registro';

COMMENT ON COLUMN CAT_STATUS_MENSAJE_ESPEJO.IP IS
'Dirección IP desde donde se realizó la operación';

-- Trigger tabla espejo
CREATE OR REPLACE TRIGGER TRG_CAT_STATUS_MENSAJE_ESPEJO
AFTER INSERT OR UPDATE
ON CAT_STATUS_MENSAJE
FOR EACH ROW

DECLARE
    V_ACCION VARCHAR2(20);

BEGIN

    IF INSERTING THEN
        V_ACCION := 'INSERT';

    ELSIF UPDATING THEN

        IF :OLD.ESTADO <> 1 AND :NEW.ESTADO = 1 THEN
            V_ACCION := 'ACTIVATE';

        ELSIF :OLD.ESTADO <> 0 AND :NEW.ESTADO = 0 THEN
            V_ACCION := 'DEACTIVATE';

        ELSE
            V_ACCION := 'UPDATE';
        END IF;

    END IF;

    INSERT INTO CAT_STATUS_MENSAJE_ESPEJO(
        UUID_STATUS_MENSAJE_ESPEJO,
        ID_STATUS_MENSAJE,
        NOMBRE_STATUS,
        DESCRIPCION,
        ESTADO,
        FECHA_CREACION,
        CREADO_POR,
        FECHA_ACTUALIZACION,
        ACTUALIZADO_POR,
        NOTAS,
        ACCION,
        IP
    )
    VALUES(
        SYS_GUID(),
        :NEW.ID_STATUS_MENSAJE,
        :NEW.NOMBRE_STATUS,
        :NEW.DESCRIPCION,
        :NEW.ESTADO,
        :NEW.FECHA_CREACION,
        :NEW.CREADO_POR,
        :NEW.FECHA_ACTUALIZACION,
        :NEW.ACTUALIZADO_POR,
        :NEW.NOTAS,
        V_ACCION,
        FN_GET_IP
    );

END;
/