-- Configurar entorno
ALTER SESSION SET CURRENT_SCHEMA = SECURITY;

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE CAT_TIPO_TOKEN_ESPEJO CASCADE CONSTRAINTS ';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TRIGGER TRG_CAT_TIPO_TOKEN_ESPEJO';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- Funcion para obtener IP
CREATE OR REPLACE FUNCTION FN_GET_IP
RETURN VARCHAR2
IS
BEGIN
    RETURN NVL(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), SYS_CONTEXT('USERENV', 'HOST'));
    EXCEPTION
        WHEN OTHERS THEN
            RETURN 'LOCALHOST';
END FN_GET_IP;
/

-- Creacion de tabla espejo
CREATE TABLE CAT_TIPO_TOKEN_ESPEJO (
    UUID_TIPO_TOKEN_ESPEJO VARCHAR2(36) NOT NULL,
    ID_TIPO_TOKEN VARCHAR2(15) NOT NULL,
    NOMBRE_TOKEN VARCHAR2(50) NOT NULL,
    DESCRIPCION VARCHAR2(100),
    ESTADO NUMBER(2) NOT NULL,
    FECHA_CREACION TIMESTAMP NOT NULL,
    CREADO_POR VARCHAR2(36) NOT NULL,
    FECHA_ACTUALIZACION TIMESTAMP,
    ACTUALIZADO_POR VARCHAR2(36),
    NOTAS VARCHAR2(100),
    ACCION VARCHAR2(20) NOT NULL,
    IP VARCHAR2(30) NOT NULL,
    CONSTRAINT PK_TIPO_TOKEN_ESPEJO PRIMARY KEY (UUID_TIPO_TOKEN_ESPEJO),
    CONSTRAINT CK_TIPO_TOKEN_ESPEJO CHECK (ESTADO IN (0, 99))
);

COMMENT ON TABLE CAT_TIPO_TOKEN_ESPEJO IS 'Tabla espejo o bitácora del catálogo tipo token';
COMMENT ON COLUMN CAT_TIPO_TOKEN_ESPEJO.UUID_TIPO_TOKEN_ESPEJO IS 'UUID único del registro espejo';
COMMENT ON COLUMN CAT_TIPO_TOKEN_ESPEJO.ID_TIPO_TOKEN IS 'Clave del tipo de token';
COMMENT ON COLUMN CAT_TIPO_TOKEN_ESPEJO.NOMBRE_TOKEN IS 'Nombre del token';
COMMENT ON COLUMN CAT_TIPO_TOKEN_ESPEJO.DESCRIPCION IS 'Descripción del token';
COMMENT ON COLUMN CAT_TIPO_TOKEN_ESPEJO.ESTADO IS '0 = Inactivo, 99 = Activo';
COMMENT ON COLUMN CAT_TIPO_TOKEN_ESPEJO.FECHA_CREACION IS 'Fecha creación del registro original';
COMMENT ON COLUMN CAT_TIPO_TOKEN_ESPEJO.CREADO_POR IS 'Usuario creador del registro original';
COMMENT ON COLUMN CAT_TIPO_TOKEN_ESPEJO.FECHA_ACTUALIZACION IS 'Fecha actualización del registro original';
COMMENT ON COLUMN CAT_TIPO_TOKEN_ESPEJO.ACTUALIZADO_POR IS 'Usuario que actualizó el registro original';
COMMENT ON COLUMN CAT_TIPO_TOKEN_ESPEJO.NOTAS IS 'Observaciones adicionales';
COMMENT ON COLUMN CAT_TIPO_TOKEN_ESPEJO.ACCION IS 'Acción realizada sobre el registro';
COMMENT ON COLUMN CAT_TIPO_TOKEN_ESPEJO.IP IS 'Dirección IP desde donde se realizó la operación';

-- Trigger tabla espejo
CREATE OR REPLACE TRIGGER TRG_CAT_TIPO_TOKEN_ESPEJO
AFTER INSERT OR UPDATE ON CAT_TIPO_TOKEN
FOR EACH ROW

DECLARE
    V_ACCION VARCHAR2(20);

BEGIN
    IF INSERTING THEN
        V_ACCION := 'INSERT';

    ELSIF UPDATING THEN
        IF :OLD.ESTADO <> 99 AND :NEW.ESTADO = 99 THEN
            V_ACCION := 'ACTIVATE';

        ELSIF :OLD.ESTADO <> 0 AND :NEW.ESTADO = 0 THEN
            V_ACCION := 'DEACTIVATE';

        ELSE
            V_ACCION := 'UPDATE';
        END IF;

    END IF;

    INSERT INTO CAT_TIPO_TOKEN_ESPEJO (
        UUID_TIPO_TOKEN_ESPEJO,
        ID_TIPO_TOKEN,
        NOMBRE_TOKEN,
        DESCRIPCION,
        ESTADO,
        FECHA_CREACION,
        CREADO_POR,
        FECHA_ACTUALIZACION,
        ACTUALIZADO_POR,
        NOTAS,
        ACCION,
        IP
    )
    VALUES (
        SYS_GUID(),
        :NEW.ID_TIPO_TOKEN,
        :NEW.NOMBRE_TOKEN,
        :NEW.DESCRIPCION,
        :NEW.ESTADO,
        :NEW.FECHA_CREACION,
        :NEW.CREADO_POR,
        :NEW.FECHA_ACTUALIZACION,
        :NEW.ACTUALIZADO_POR,
        :NEW.NOTAS,
        V_ACCION,
        FN_GET_IP
    );

END;
/