-- Configurar entorno
ALTER SESSION SET CURRENT_SCHEMA = SECURITY;

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE CLIENTES_ESPEJO CASCADE CONSTRAINTS ';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TRIGGER TRG_CLIENTES_ESPEJO';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- Funcion para obtener IP
CREATE OR REPLACE FUNCTION FN_GET_IP
RETURN VARCHAR2
IS
BEGIN
    RETURN NVL(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), SYS_CONTEXT('USERENV', 'HOST'));
    EXCEPTION
        WHEN OTHERS THEN
            RETURN 'LOCALHOST';
END FN_GET_IP;
/

-- Creacion de tabla espejo
CREATE TABLE CLIENTES_ESPEJO (
    UUID_CLIENTE_ESPEJO VARCHAR2(36) NOT NULL,
    ID_CLIENTE VARCHAR2(36) NOT NULL,
    NOMBRE VARCHAR2(40) NOT NULL,
    APATERNO VARCHAR2(40) NOT NULL,
    AMATERNO VARCHAR2(40),
    EMAIL VARCHAR2(100),
    FECHA_ALTA DATE DEFAULT SYSDATE,
    ESTADO NUMBER(2) NOT NULL,
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREADO_POR VARCHAR2(36) NOT NULL,
    FECHA_ACTUALIZACION TIMESTAMP,
    ACTUALIZADO_POR VARCHAR2(36),
    NOTAS VARCHAR2(100),
    ACCION VARCHAR2(20) NOT NULL,
    IP VARCHAR2(30) NOT NULL,
    CONSTRAINT PK_CLIENTES_ESPEJO PRIMARY KEY (UUID_CLIENTE_ESPEJO)
);

COMMENT ON TABLE CLIENTES_ESPEJO IS 'Tabla espejo o bitácora de clientes';
COMMENT ON COLUMN CLIENTES_ESPEJO.UUID_CLIENTE_ESPEJO IS 'UUID único del registro espejo';
COMMENT ON COLUMN CLIENTES_ESPEJO.ID_CLIENTE IS 'Llave primaria del cliente';
COMMENT ON COLUMN CLIENTES_ESPEJO.NOMBRE IS 'Nombre del cliente';
COMMENT ON COLUMN CLIENTES_ESPEJO.APATERNO IS 'Apellido paterno';
COMMENT ON COLUMN CLIENTES_ESPEJO.AMATERNO IS 'Apellido materno';
COMMENT ON COLUMN CLIENTES_ESPEJO.EMAIL IS 'Email del cliente';
COMMENT ON COLUMN CLIENTES_ESPEJO.FECHA_ALTA IS 'Fecha de alta del cliente';
COMMENT ON COLUMN CLIENTES_ESPEJO.ESTADO IS 'Bandera para borrado lógico';
COMMENT ON COLUMN CLIENTES_ESPEJO.FECHA_CREACION IS 'Fecha creación del registro original';
COMMENT ON COLUMN CLIENTES_ESPEJO.CREADO_POR IS 'Usuario creador del registro original';
COMMENT ON COLUMN CLIENTES_ESPEJO.FECHA_ACTUALIZACION IS 'Fecha actualización del registro original';
COMMENT ON COLUMN CLIENTES_ESPEJO.ACTUALIZADO_POR IS 'Usuario que actualizó el registro original';
COMMENT ON COLUMN CLIENTES_ESPEJO.NOTAS IS 'Observaciones adicionales';
COMMENT ON COLUMN CLIENTES_ESPEJO.ACCION IS 'Acción realizada sobre el registro';
COMMENT ON COLUMN CLIENTES_ESPEJO.IP IS 'Dirección IP desde donde se realizó la operación';

-- Trigger tabla espejo
CREATE OR REPLACE TRIGGER TRG_CLIENTES_ESPEJO
AFTER INSERT OR UPDATE ON CLIENTES
FOR EACH ROW

DECLARE
    V_ACCION VARCHAR2(20);
    V_FECHA_CREACION TIMESTAMP := NULL;
    V_FECHA_ACTUALIZACION TIMESTAMP := NULL;

BEGIN

    IF INSERTING THEN

        V_ACCION := 'INSERT';
        V_FECHA_CREACION := :NEW.FECHA_CREACION;

    ELSIF UPDATING THEN

        V_FECHA_CREACION := :OLD.FECHA_CREACION;
        V_FECHA_ACTUALIZACION := CURRENT_TIMESTAMP;

        IF :OLD.ESTADO = 99 AND :NEW.ESTADO = 0 THEN
            V_ACCION := 'DEACTIVATE';

        ELSIF :OLD.ESTADO = 0 AND :NEW.ESTADO = 99 THEN
            V_ACCION := 'ACTIVATE';

        ELSE
            V_ACCION := 'UPDATE';
        END IF;

    END IF;

    INSERT INTO CLIENTES_ESPEJO (
        UUID_CLIENTE_ESPEJO,
        ID_CLIENTE,
        NOMBRE,
        APATERNO,
        AMATERNO,
        EMAIL,
        FECHA_ALTA,
        ESTADO,
        FECHA_CREACION,
        FECHA_ACTUALIZACION,
        CREADO_POR,
        ACTUALIZADO_POR,
        NOTAS,
        ACCION,
        IP
    )
    VALUES (
        SYS_GUID(),
        :NEW.ID_CLIENTE,
        :NEW.NOMBRE,
        :NEW.APATERNO,
        :NEW.AMATERNO,
        :NEW.EMAIL,
        :NEW.FECHA_ALTA,
        :NEW.ESTADO,
        V_FECHA_CREACION,
        V_FECHA_ACTUALIZACION,
        :NEW.CREADO_POR,
        :NEW.ACTUALIZADO_POR,
        :NEW.NOTAS,
        V_ACCION,
        FN_GET_IP()
    );

END;
/