-- Configurar entorno
ALTER SESSION SET CURRENT_SCHEMA = SECURITY;

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE DATOS_FISCALES_ESPEJO CASCADE CONSTRAINTS ';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TRIGGER TRG_DATOS_FISCALES_ESPEJO';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- Funcion para obtener IP
CREATE OR REPLACE FUNCTION FN_GET_IP
RETURN VARCHAR2
IS
BEGIN
    RETURN NVL(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), SYS_CONTEXT('USERENV', 'HOST'));
    EXCEPTION
        WHEN OTHERS THEN
            RETURN 'LOCALHOST';
END FN_GET_IP;
/

-- Creacion de tabla espejo
CREATE TABLE DATOS_FISCALES_ESPEJO (
    UUID_DATOS_FISCALES_ESPEJO VARCHAR2(36) NOT NULL,
    ID_DATOSFISC VARCHAR2(36) NOT NULL,
    ID_CLIENTE VARCHAR2(36) NOT NULL,
    RAZON_SOCIAL VARCHAR2(150) NOT NULL,
    RFC VARCHAR2(13) NOT NULL,
    CODIGO_POSTAL VARCHAR2(5) NOT NULL,
    ID_TIPO_CLIENTE VARCHAR2(3) NOT NULL,
    USO_CFDI VARCHAR2(3) NOT NULL,
    EMAIL VARCHAR2(100),
    D_ESTADO VARCHAR2(36) NOT NULL,
    D_CIUDAD VARCHAR2(36) NOT NULL,
    D_COLONIA VARCHAR2(36) NOT NULL,
    D_ZONA VARCHAR2(36) NOT NULL,
    CREATED_AT DATE DEFAULT SYSDATE,
    STATUS NUMBER(2) NOT NULL,
    CREADO_POR VARCHAR2(36) NOT NULL,
    FECHA_ACTUALIZACION TIMESTAMP,
    ACTUALIZADO_POR VARCHAR2(36),
    NOTAS VARCHAR2(100),
    ACCION VARCHAR2(20) NOT NULL,
    IP VARCHAR2(30) NOT NULL,
    CONSTRAINT PK_DATOS_FISCALES_ESPEJO PRIMARY KEY (UUID_DATOS_FISCALES_ESPEJO)
);

COMMENT ON TABLE DATOS_FISCALES_ESPEJO IS 'Tabla espejo o bitácora de datos fiscales';
COMMENT ON COLUMN DATOS_FISCALES_ESPEJO.UUID_DATOS_FISCALES_ESPEJO IS 'UUID único del registro espejo';
COMMENT ON COLUMN DATOS_FISCALES_ESPEJO.ID_DATOSFISC IS 'Llave primaria del registro fiscal';
COMMENT ON COLUMN DATOS_FISCALES_ESPEJO.ID_CLIENTE IS 'Identificador del cliente';
COMMENT ON COLUMN DATOS_FISCALES_ESPEJO.RAZON_SOCIAL IS 'Razón social registrada en SAT';
COMMENT ON COLUMN DATOS_FISCALES_ESPEJO.RFC IS 'RFC del cliente';
COMMENT ON COLUMN DATOS_FISCALES_ESPEJO.CODIGO_POSTAL IS 'Código postal fiscal';
COMMENT ON COLUMN DATOS_FISCALES_ESPEJO.ID_TIPO_CLIENTE IS 'Tipo de cliente';
COMMENT ON COLUMN DATOS_FISCALES_ESPEJO.USO_CFDI IS 'Uso del CFDI';
COMMENT ON COLUMN DATOS_FISCALES_ESPEJO.EMAIL IS 'Email del cliente';
COMMENT ON COLUMN DATOS_FISCALES_ESPEJO.D_ESTADO IS 'Estado';
COMMENT ON COLUMN DATOS_FISCALES_ESPEJO.D_CIUDAD IS 'Ciudad';
COMMENT ON COLUMN DATOS_FISCALES_ESPEJO.D_COLONIA IS 'Colonia';
COMMENT ON COLUMN DATOS_FISCALES_ESPEJO.D_ZONA IS 'Zona';
COMMENT ON COLUMN DATOS_FISCALES_ESPEJO.CREATED_AT IS 'Fecha creación registro original';
COMMENT ON COLUMN DATOS_FISCALES_ESPEJO.STATUS IS 'Bandera borrado lógico';
COMMENT ON COLUMN DATOS_FISCALES_ESPEJO.CREADO_POR IS 'Usuario creador del registro original';
COMMENT ON COLUMN DATOS_FISCALES_ESPEJO.FECHA_ACTUALIZACION IS 'Fecha actualización del registro original';
COMMENT ON COLUMN DATOS_FISCALES_ESPEJO.ACTUALIZADO_POR IS 'Usuario que actualizó el registro original';
COMMENT ON COLUMN DATOS_FISCALES_ESPEJO.NOTAS IS 'Observaciones adicionales';
COMMENT ON COLUMN DATOS_FISCALES_ESPEJO.ACCION IS 'Acción realizada sobre el registro';
COMMENT ON COLUMN DATOS_FISCALES_ESPEJO.IP IS 'Dirección IP desde donde se realizó la operación';

-- Trigger tabla espejo
CREATE OR REPLACE TRIGGER TRG_DATOS_FISCALES_ESPEJO
AFTER INSERT OR UPDATE ON DATOS_FISCALES
FOR EACH ROW

DECLARE
    V_ACCION VARCHAR2(20);

BEGIN

    IF INSERTING THEN
        V_ACCION := 'INSERT';

    ELSIF UPDATING THEN

        IF :OLD.STATUS <> 1 AND :NEW.STATUS = 1 THEN
            V_ACCION := 'ACTIVATE';

        ELSIF :OLD.STATUS <> 0 AND :NEW.STATUS = 0 THEN
            V_ACCION := 'DEACTIVATE';

        ELSE
            V_ACCION := 'UPDATE';
        END IF;

    END IF;

    INSERT INTO DATOS_FISCALES_ESPEJO (
        UUID_DATOS_FISCALES_ESPEJO,
        ID_DATOSFISC,
        ID_CLIENTE,
        RAZON_SOCIAL,
        RFC,
        CODIGO_POSTAL,
        ID_TIPO_CLIENTE,
        USO_CFDI,
        EMAIL,
        D_ESTADO,
        D_CIUDAD,
        D_COLONIA,
        D_ZONA,
        CREATED_AT,
        STATUS,
        CREADO_POR,
        FECHA_ACTUALIZACION,
        ACTUALIZADO_POR,
        NOTAS,
        ACCION,
        IP
    )
    VALUES (
        SYS_GUID(),
        :NEW.ID_DATOSFISC,
        :NEW.ID_CLIENTE,
        :NEW.RAZON_SOCIAL,
        :NEW.RFC,
        :NEW.CODIGO_POSTAL,
        :NEW.ID_TIPO_CLIENTE,
        :NEW.USO_CFDI,
        :NEW.EMAIL,
        :NEW.D_ESTADO,
        :NEW.D_CIUDAD,
        :NEW.D_COLONIA,
        :NEW.D_ZONA,
        :NEW.CREATED_AT,
        :NEW.STATUS,
        :NEW.CREADO_POR,
        :NEW.FECHA_ACTUALIZACION,
        :NEW.ACTUALIZADO_POR,
        :NEW.NOTAS,
        V_ACCION,
        FN_GET_IP()
    );

END;
/