-- Configurar entorno
ALTER SESSION SET CURRENT_SCHEMA = SECURITY;

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE FACTURAS_ESPEJO CASCADE CONSTRAINTS ';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TRIGGER TRG_FACTURAS_ESPEJO';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- Funcion para obtener IP
CREATE OR REPLACE FUNCTION FN_GET_IP
RETURN VARCHAR2
IS
BEGIN
    RETURN NVL(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), SYS_CONTEXT('USERENV', 'HOST'));
    EXCEPTION
        WHEN OTHERS THEN
            RETURN 'LOCALHOST';
END FN_GET_IP;
/

-- Creacion de tabla espejo
CREATE TABLE FACTURAS_ESPEJO (
    UUID_FACTURA_ESPEJO VARCHAR2(36) NOT NULL,
    ID_FACTURA VARCHAR2(36) NOT NULL,
    ID_CLIENTE VARCHAR2(36) NOT NULL,
    MONTO_TOTAL NUMBER(10, 2) NOT NULL,
    FOLIO NUMBER NOT NULL,
    ANIO NUMBER(4) NOT NULL,
    ID_ESTADO_FACTURA VARCHAR2(15) NOT NULL,
    FECHA_FACTURA DATE DEFAULT SYSDATE,
    ESTADO NUMBER(2) NOT NULL,
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREADO_POR VARCHAR2(36) NOT NULL,
    FECHA_ACTUALIZACION TIMESTAMP,
    ACTUALIZADO_POR VARCHAR2(36),
    NOTAS VARCHAR2(100),
    ACCION VARCHAR2(20) NOT NULL,
    IP VARCHAR2(30) NOT NULL,
    CONSTRAINT PK_FACTURAS_ESPEJO PRIMARY KEY (UUID_FACTURA_ESPEJO)
);

COMMENT ON TABLE FACTURAS_ESPEJO IS 'Tabla espejo o bitácora de facturas';
COMMENT ON COLUMN FACTURAS_ESPEJO.UUID_FACTURA_ESPEJO IS 'UUID único del registro espejo';
COMMENT ON COLUMN FACTURAS_ESPEJO.ID_FACTURA IS 'Id de la factura';
COMMENT ON COLUMN FACTURAS_ESPEJO.ID_CLIENTE IS 'Id del cliente';
COMMENT ON COLUMN FACTURAS_ESPEJO.MONTO_TOTAL IS 'Monto total de la factura';
COMMENT ON COLUMN FACTURAS_ESPEJO.FOLIO IS 'Folio de la factura';
COMMENT ON COLUMN FACTURAS_ESPEJO.ANIO IS 'Año de la factura';
COMMENT ON COLUMN FACTURAS_ESPEJO.ID_ESTADO_FACTURA IS 'Estado de la factura';
COMMENT ON COLUMN FACTURAS_ESPEJO.FECHA_FACTURA IS 'Fecha de la factura';
COMMENT ON COLUMN FACTURAS_ESPEJO.ESTADO IS 'Bandera para borrado lógico';
COMMENT ON COLUMN FACTURAS_ESPEJO.FECHA_CREACION IS 'Fecha creación del registro original';
COMMENT ON COLUMN FACTURAS_ESPEJO.CREADO_POR IS 'Usuario creador del registro original';
COMMENT ON COLUMN FACTURAS_ESPEJO.FECHA_ACTUALIZACION IS 'Fecha actualización del registro original';
COMMENT ON COLUMN FACTURAS_ESPEJO.ACTUALIZADO_POR IS 'Usuario que actualizó el registro original';
COMMENT ON COLUMN FACTURAS_ESPEJO.NOTAS IS 'Observaciones adicionales';
COMMENT ON COLUMN FACTURAS_ESPEJO.ACCION IS 'Acción realizada sobre el registro';
COMMENT ON COLUMN FACTURAS_ESPEJO.IP IS 'Dirección IP desde donde se realizó la operación';

-- Trigger tabla espejo
CREATE OR REPLACE TRIGGER TRG_FACTURAS_ESPEJO
AFTER INSERT OR UPDATE ON FACTURAS
FOR EACH ROW

DECLARE
    V_ACCION VARCHAR2(20);

BEGIN

    IF INSERTING THEN
        V_ACCION := 'INSERT';

    ELSIF UPDATING THEN

        IF :OLD.ESTADO <> 1 AND :NEW.ESTADO = 1 THEN
            V_ACCION := 'ACTIVATE';

        ELSIF :OLD.ESTADO <> 0 AND :NEW.ESTADO = 0 THEN
            V_ACCION := 'DEACTIVATE';

        ELSE
            V_ACCION := 'UPDATE';
        END IF;

    END IF;

    INSERT INTO FACTURAS_ESPEJO (
        UUID_FACTURA_ESPEJO,
        ID_FACTURA,
        ID_CLIENTE,
        MONTO_TOTAL,
        FOLIO,
        ANIO,
        ID_ESTADO_FACTURA,
        FECHA_FACTURA,
        ESTADO,
        FECHA_CREACION,
        CREADO_POR,
        FECHA_ACTUALIZACION,
        ACTUALIZADO_POR,
        NOTAS,
        ACCION,
        IP
    )
    VALUES (
        SYS_GUID(),
        :NEW.ID_FACTURA,
        :NEW.ID_CLIENTE,
        :NEW.MONTO_TOTAL,
        :NEW.FOLIO,
        :NEW.ANIO,
        :NEW.ID_ESTADO_FACTURA,
        :NEW.FECHA_FACTURA,
        :NEW.ESTADO,
        :NEW.FECHA_CREACION,
        :NEW.CREADO_POR,
        :NEW.FECHA_ACTUALIZACION,
        :NEW.ACTUALIZADO_POR,
        :NEW.NOTAS,
        V_ACCION,
        FN_GET_IP()
    );

END;
/