-- Configurar entorno
ALTER SESSION SET CURRENT_SCHEMA = SECURITY;

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE MENSAJE_CONTACTO_ESPEJO CASCADE CONSTRAINTS ';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TRIGGER TRG_MENSAJE_CONTACTO_ESPEJO';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- Funcion para obtener IP
CREATE OR REPLACE FUNCTION FN_GET_IP
RETURN VARCHAR2
IS
BEGIN
    RETURN NVL(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), SYS_CONTEXT('USERENV', 'HOST'));
    EXCEPTION
        WHEN OTHERS THEN
            RETURN 'LOCALHOST';
END FN_GET_IP;
/

-- Creacion de tabla espejo
CREATE TABLE MENSAJE_CONTACTO_ESPEJO (
    UUID_MENSAJE_CONTACTO_ESPEJO VARCHAR2(36) NOT NULL,
    ID_MENSAJE VARCHAR2(36) NOT NULL,
    NOMBRE VARCHAR2(40) NOT NULL,
    CORREO VARCHAR2(60) NOT NULL,
    DESCRIPCION VARCHAR2(1000) NOT NULL,
    ACTIVO NUMBER(1) NOT NULL,
    FECHA_ENVIO DATE DEFAULT SYSDATE,
    ID_ESTATUS_MENSAJE VARCHAR2(15) NOT NULL,
    USUARIO_RESPUESTA VARCHAR2(40) NOT NULL,
    ESTADO NUMBER(2) NOT NULL,
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREADO_POR VARCHAR2(36) NOT NULL,
    FECHA_ACTUALIZACION TIMESTAMP,
    ACTUALIZADO_POR VARCHAR2(36),
    NOTAS VARCHAR2(100),
    ACCION VARCHAR2(20) NOT NULL,
    IP VARCHAR2(30) NOT NULL,
    CONSTRAINT PK_MENSAJE_CONTACTO_ESPEJO PRIMARY KEY (UUID_MENSAJE_CONTACTO_ESPEJO)
);

COMMENT ON TABLE MENSAJE_CONTACTO_ESPEJO IS 'Tabla espejo o bitácora de mensajes de contacto';
COMMENT ON COLUMN MENSAJE_CONTACTO_ESPEJO.UUID_MENSAJE_CONTACTO_ESPEJO IS 'UUID único del registro espejo';
COMMENT ON COLUMN MENSAJE_CONTACTO_ESPEJO.ID_MENSAJE IS 'Id del mensaje';
COMMENT ON COLUMN MENSAJE_CONTACTO_ESPEJO.NOMBRE IS 'Nombre del usuario';
COMMENT ON COLUMN MENSAJE_CONTACTO_ESPEJO.CORREO IS 'Correo electrónico';
COMMENT ON COLUMN MENSAJE_CONTACTO_ESPEJO.DESCRIPCION IS 'Descripción del mensaje';
COMMENT ON COLUMN MENSAJE_CONTACTO_ESPEJO.ACTIVO IS 'Bandera de activo';
COMMENT ON COLUMN MENSAJE_CONTACTO_ESPEJO.FECHA_ENVIO IS 'Fecha de envío';
COMMENT ON COLUMN MENSAJE_CONTACTO_ESPEJO.ID_ESTATUS_MENSAJE IS 'Estado del mensaje';
COMMENT ON COLUMN MENSAJE_CONTACTO_ESPEJO.USUARIO_RESPUESTA IS 'Usuario que responde';
COMMENT ON COLUMN MENSAJE_CONTACTO_ESPEJO.ESTADO IS 'Bandera para borrado lógico';
COMMENT ON COLUMN MENSAJE_CONTACTO_ESPEJO.FECHA_CREACION IS 'Fecha creación del registro original';
COMMENT ON COLUMN MENSAJE_CONTACTO_ESPEJO.CREADO_POR IS 'Usuario creador del registro original';
COMMENT ON COLUMN MENSAJE_CONTACTO_ESPEJO.FECHA_ACTUALIZACION IS 'Fecha actualización del registro original';
COMMENT ON COLUMN MENSAJE_CONTACTO_ESPEJO.ACTUALIZADO_POR IS 'Usuario que actualizó el registro original';
COMMENT ON COLUMN MENSAJE_CONTACTO_ESPEJO.NOTAS IS 'Observaciones adicionales';
COMMENT ON COLUMN MENSAJE_CONTACTO_ESPEJO.ACCION IS 'Acción realizada sobre el registro';
COMMENT ON COLUMN MENSAJE_CONTACTO_ESPEJO.IP IS 'Dirección IP desde donde se realizó la operación';

-- Trigger tabla espejo
CREATE OR REPLACE TRIGGER TRG_MENSAJE_CONTACTO_ESPEJO
AFTER INSERT OR UPDATE ON MENSAJE_CONTACTO
FOR EACH ROW

DECLARE
    V_ACCION VARCHAR2(20);

BEGIN

    IF INSERTING THEN
        V_ACCION := 'INSERT';

    ELSIF UPDATING THEN

        IF :OLD.ESTADO <> 1 AND :NEW.ESTADO = 1 THEN
            V_ACCION := 'ACTIVATE';

        ELSIF :OLD.ESTADO <> 0 AND :NEW.ESTADO = 0 THEN
            V_ACCION := 'DEACTIVATE';

        ELSE
            V_ACCION := 'UPDATE';
        END IF;

    END IF;

    INSERT INTO MENSAJE_CONTACTO_ESPEJO (
        UUID_MENSAJE_CONTACTO_ESPEJO,
        ID_MENSAJE,
        NOMBRE,
        CORREO,
        DESCRIPCION,
        ACTIVO,
        FECHA_ENVIO,
        ID_ESTATUS_MENSAJE,
        USUARIO_RESPUESTA,
        ESTADO,
        FECHA_CREACION,
        CREADO_POR,
        FECHA_ACTUALIZACION,
        ACTUALIZADO_POR,
        NOTAS,
        ACCION,
        IP
    )
    VALUES (
        SYS_GUID(),
        :NEW.ID_MENSAJE,
        :NEW.NOMBRE,
        :NEW.CORREO,
        :NEW.DESCRIPCION,
        :NEW.ACTIVO,
        :NEW.FECHA_ENVIO,
        :NEW.ID_ESTATUS_MENSAJE,
        :NEW.USUARIO_RESPUESTA,
        :NEW.ESTADO,
        :NEW.FECHA_CREACION,
        :NEW.CREADO_POR,
        :NEW.FECHA_ACTUALIZACION,
        :NEW.ACTUALIZADO_POR,
        :NEW.NOTAS,
        V_ACCION,
        FN_GET_IP()
    );

END;
/